<header class='o-header-services' data-o-component='o-header-services'>
	<div class='o-header-services__top o-header-services__container'>
		<div class='o-grid-row'>
			<a href="/" class='o-header-services__ftlogo'></a>
			<div class='o-header-services__title'>
				<h1 class='o-header-services__product-name'>System Registry</h1>
				<span class='o-header-subrand__product-tagline'>Maintain System Information</span>
			</div>
		</div>
	</div>
</header>
